import type { Project, UserInfo } from "../type";

export function mapDataToProject(currentToken: any): Project {
  return {
    id: currentToken.id,
    address: currentToken.address,
    tokenName: currentToken.token_name,
    tokenSymbol: currentToken.token_symbol,
    ticker: currentToken.ticker,
    about: currentToken.about_us,
    website: currentToken.website,
    tokenIcon: currentToken.icon || currentToken.video,
    token_icon: currentToken.icon,
    tokenImg: currentToken.video || currentToken.icon,
    token_video: currentToken.video,
    tokenDecimals: currentToken.token_decimals,
    isLike: currentToken.is_like,
    isUnLike: currentToken.is_un_like,
    isSuperLike: currentToken.is_pre_paid,
    like: currentToken.like,
    unLike: currentToken.un_like,
    superLike: currentToken.super_like,
    time: currentToken.time,
    account: currentToken.account,
    creater: currentToken.account_data,
    boostTime: currentToken.boost_time,
    status: currentToken.status,
    createdAt: new Date(currentToken.created_at).getTime(),
    DApp: currentToken.DApp,
    initiativeLaunching: currentToken.initiative_launching,
    prePaidAmount: currentToken.pre_paid_amount,
    prePaid: currentToken.pre_paid,
    x: currentToken.x,
    tg: currentToken.tg,
    discord: currentToken.discord,
    comment: currentToken.comment,
    bondingProgress: currentToken.bonding_progress,
    kingProgress: currentToken.king_progress,
    isKing: currentToken.is_king,
    lastKingTime: currentToken.last_king_time,
    timeLeft: currentToken.time + 3 * 60 * 60 * 1000,
    price: currentToken.price,
    tx: currentToken.tx,
    sells24hUsd: currentToken.sells_24h_usd,
    buys24hUsd: currentToken.buys_24h_usd,
    marketCap24hUsd: currentToken.market_cap_24h_usd,
    volume24hUsd: currentToken.volume_24h_usd,
    mc: currentToken.market_cap,
    solReserve: currentToken.sol_reserve,
    ...currentToken
  };
}

export function mapDataToUser(item: any): UserInfo {
  return {
    name: item.name,
    address: item.address,
    icon: item.icon,
    banner: item.banner,
    followers: item.followers,
    following: item.following,
    likeNum: item.like_num,
    boostNum: item.boost_num,
    usingBoostNum: item.using_boost_num,
    superLikeNum: item.super_like_num,
    usingSuperLikeNum: item.using_super_like_num,
    usingBuySuperLikeNum: item.using_buy_super_like_num,
    vipType: item.vip_type,
    isFollower: item.is_follower,
    ...item
  };
}
